[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello_sol = "4cScV6fN82gEnZhL3quiSXfj3FVU4YdYA6sjG3zXsT2L"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
